baseURL = 'https://nacharya.github.io/'
languageCode = 'en'
title = 'N Acharya'
theme = 'blowfish'
enableEmoji = true

[module]
  [[module.imports]]
    path = 'modules/google-adsense'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
